name: build
channels:
  - conda-forge
  - mdtools
dependencies:
    # Base depends
  - python
  - pip
  - numpy
  - openmm
  - pandas
  - pyyaml
  - scipy
  - cvpack

    # Conda build
  - anaconda-client
  - conda-build
  - boa
