{% set version = environ['UFEDMM_VERSION'][1:] %}

package:
  name: ufedmm
  version: {{ version }}

source:
  git_url: ../../../

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - versioningit
    - pip
  run:
    - python
    - importlib-resources  # [py<310]
    - numpy
    - openmm
    - pandas
    - pyyaml
    - scipy
    - cvpack

test:
  imports:
    - ufedmm

about:
  home: https://github.com/craabreu/ufedmm
  summary: Unified Free Energy Dynamics with OpenMM
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://craabreu.github.io/ufedmm
  dev_url: https://github.com/craabreu/ufedmm

extra:
  recipe-maintainers:
    - craabreu
