name: Anaconda

on:
  push:
    tags:
      - v*

jobs:
  test:
    name: Build on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: devtools/conda-envs/conda_build_env.yaml
          environment-name: test
          channels: conda-forge
          extra-specs: |
            python=${{ matrix.python-version }}

      - name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          micromamba list

      - name: Conda Build and Upload
        shell: bash -l {0}
        working-directory: ./devtools/conda-recipes/anaconda
        run: |
          dir=$(mktemp -d)
          export UFEDMM_VERSION=${{ github.ref_name }}
          for version in 3.{8..11}; do
            echo "::group::Building ufedmm $UFEDMM_VERSION for Python $version"
            outdir=$dir/py$version
            mkdir $outdir
            export PYTHON_VERSION=$version
            conda mambabuild . --no-anaconda-upload -c conda-forge --output-folder $outdir --python $version
            PACKAGE=$(find $outdir -name *.tar.bz2 | head -1)
            for platform in osx-64 linux-32 linux-64 win-32 win-64; do
              echo "Converting package to platform $platform"
              conda convert --platform $platform $PACKAGE -o $outdir
            done
            echo "::endgroup::"
          done
          export ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
          echo "::group::Uploading packages to redesign-science conda channel"
          for filename in $(find $dir -name *.tar.bz2); do
            anaconda upload --user redesign-science --force --label main $filename
          done
          echo "::endgroup::"
